[package]
name = "scpmapper"
version = "0.1.1"
authors = ["grufkork <griffin.hiscoke@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inputbot = "0.5.0"